//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCIDLA.ServiceClient.TMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TMS.ITemplate")]
    public interface ITemplate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemplate/GetTemplate", ReplyAction="http://tempuri.org/ITemplate/GetTemplateResponse")]
        byte[] GetTemplate(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITemplate/GetTemplate", ReplyAction="http://tempuri.org/ITemplate/GetTemplateResponse")]
        System.Threading.Tasks.Task<byte[]> GetTemplateAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITemplateChannel : HCIDLA.ServiceClient.TMS.ITemplate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TemplateClient : System.ServiceModel.ClientBase<HCIDLA.ServiceClient.TMS.ITemplate>, HCIDLA.ServiceClient.TMS.ITemplate {
        
        public TemplateClient() {
        }
        
        public TemplateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemplateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemplateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemplateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetTemplate(string data) {
            return base.Channel.GetTemplate(data);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetTemplateAsync(string data) {
            return base.Channel.GetTemplateAsync(data);
        }
    }
}
