//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCIDLA.ServiceClient.DTS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationNameEnum", Namespace="http://schemas.datacontract.org/2004/07/DownTimeScheduler.WcfIISHostBasicService")]
    public enum ApplicationNameEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIMSIntranet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIMSCP = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIMSMobile = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRIS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRISIntranet = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CPRAIntranet = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EARFormIntranet = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FIMS = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FIMSIntranet = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        G2G = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRAdminIntranet = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RENT = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RENTIntranet = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIMS = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIMSIntranet = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NspWebPortalExternal = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChpsExternal = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HopwaExtenal = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NofaExternal = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcHPIntranet = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcHPWeb = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LandUse = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THPCP = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THPStaffInternet = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THPStaffIntranet = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AAHRInternetTest = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AAHRIntranetTest = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AAHRStageInternetLAHousingDev = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AAHRInternetLAHousing = 28,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schedule", Namespace="http://schemas.datacontract.org/2004/07/DownTimeScheduler.DataAccess.Models")]
    [System.SerializableAttribute()]
    public partial class Schedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AdvanceNoticeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayReminderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeletedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeletedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DowntimeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsDowntimeSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsReminderSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsUptimeSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReminderEmailListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ScheduleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShutdownMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UptimeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarningMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isShutdownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AdvanceNoticeDate {
            get {
                return this.AdvanceNoticeDateField;
            }
            set {
                if ((this.AdvanceNoticeDateField.Equals(value) != true)) {
                    this.AdvanceNoticeDateField = value;
                    this.RaisePropertyChanged("AdvanceNoticeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationList {
            get {
                return this.ApplicationListField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationListField, value) != true)) {
                    this.ApplicationListField = value;
                    this.RaisePropertyChanged("ApplicationList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DayReminder {
            get {
                return this.DayReminderField;
            }
            set {
                if ((this.DayReminderField.Equals(value) != true)) {
                    this.DayReminderField = value;
                    this.RaisePropertyChanged("DayReminder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeletedBy {
            get {
                return this.DeletedByField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedByField, value) != true)) {
                    this.DeletedByField = value;
                    this.RaisePropertyChanged("DeletedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeletedDate {
            get {
                return this.DeletedDateField;
            }
            set {
                if ((this.DeletedDateField.Equals(value) != true)) {
                    this.DeletedDateField = value;
                    this.RaisePropertyChanged("DeletedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DowntimeDate {
            get {
                return this.DowntimeDateField;
            }
            set {
                if ((this.DowntimeDateField.Equals(value) != true)) {
                    this.DowntimeDateField = value;
                    this.RaisePropertyChanged("DowntimeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsDowntimeSet {
            get {
                return this.IsDowntimeSetField;
            }
            set {
                if ((this.IsDowntimeSetField.Equals(value) != true)) {
                    this.IsDowntimeSetField = value;
                    this.RaisePropertyChanged("IsDowntimeSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsReminderSent {
            get {
                return this.IsReminderSentField;
            }
            set {
                if ((this.IsReminderSentField.Equals(value) != true)) {
                    this.IsReminderSentField = value;
                    this.RaisePropertyChanged("IsReminderSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsUptimeSet {
            get {
                return this.IsUptimeSetField;
            }
            set {
                if ((this.IsUptimeSetField.Equals(value) != true)) {
                    this.IsUptimeSetField = value;
                    this.RaisePropertyChanged("IsUptimeSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReminderEmailList {
            get {
                return this.ReminderEmailListField;
            }
            set {
                if ((object.ReferenceEquals(this.ReminderEmailListField, value) != true)) {
                    this.ReminderEmailListField = value;
                    this.RaisePropertyChanged("ReminderEmailList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ScheduleId {
            get {
                return this.ScheduleIdField;
            }
            set {
                if ((this.ScheduleIdField.Equals(value) != true)) {
                    this.ScheduleIdField = value;
                    this.RaisePropertyChanged("ScheduleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShutdownMessage {
            get {
                return this.ShutdownMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ShutdownMessageField, value) != true)) {
                    this.ShutdownMessageField = value;
                    this.RaisePropertyChanged("ShutdownMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UptimeDate {
            get {
                return this.UptimeDateField;
            }
            set {
                if ((this.UptimeDateField.Equals(value) != true)) {
                    this.UptimeDateField = value;
                    this.RaisePropertyChanged("UptimeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarningMessage {
            get {
                return this.WarningMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningMessageField, value) != true)) {
                    this.WarningMessageField = value;
                    this.RaisePropertyChanged("WarningMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isShutdown {
            get {
                return this.isShutdownField;
            }
            set {
                if ((this.isShutdownField.Equals(value) != true)) {
                    this.isShutdownField = value;
                    this.RaisePropertyChanged("isShutdown");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DTS.IDownTimeScheduler")]
    public interface IDownTimeScheduler {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownTimeScheduler/GetApplicationDowntimeSchedule", ReplyAction="http://tempuri.org/IDownTimeScheduler/GetApplicationDowntimeScheduleResponse")]
        HCIDLA.ServiceClient.DTS.Schedule GetApplicationDowntimeSchedule(HCIDLA.ServiceClient.DTS.ApplicationNameEnum applicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownTimeScheduler/GetApplicationDowntimeSchedule", ReplyAction="http://tempuri.org/IDownTimeScheduler/GetApplicationDowntimeScheduleResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.DTS.Schedule> GetApplicationDowntimeScheduleAsync(HCIDLA.ServiceClient.DTS.ApplicationNameEnum applicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownTimeScheduler/GetApplicationDowntimeScheduleByApplication" +
            "Name", ReplyAction="http://tempuri.org/IDownTimeScheduler/GetApplicationDowntimeScheduleByApplication" +
            "NameResponse")]
        HCIDLA.ServiceClient.DTS.Schedule GetApplicationDowntimeScheduleByApplicationName(string applicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDownTimeScheduler/GetApplicationDowntimeScheduleByApplication" +
            "Name", ReplyAction="http://tempuri.org/IDownTimeScheduler/GetApplicationDowntimeScheduleByApplication" +
            "NameResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.DTS.Schedule> GetApplicationDowntimeScheduleByApplicationNameAsync(string applicationName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDownTimeSchedulerChannel : HCIDLA.ServiceClient.DTS.IDownTimeScheduler, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DownTimeSchedulerClient : System.ServiceModel.ClientBase<HCIDLA.ServiceClient.DTS.IDownTimeScheduler>, HCIDLA.ServiceClient.DTS.IDownTimeScheduler {
        
        public DownTimeSchedulerClient() {
        }
        
        public DownTimeSchedulerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DownTimeSchedulerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownTimeSchedulerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DownTimeSchedulerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HCIDLA.ServiceClient.DTS.Schedule GetApplicationDowntimeSchedule(HCIDLA.ServiceClient.DTS.ApplicationNameEnum applicationName) {
            return base.Channel.GetApplicationDowntimeSchedule(applicationName);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.DTS.Schedule> GetApplicationDowntimeScheduleAsync(HCIDLA.ServiceClient.DTS.ApplicationNameEnum applicationName) {
            return base.Channel.GetApplicationDowntimeScheduleAsync(applicationName);
        }
        
        public HCIDLA.ServiceClient.DTS.Schedule GetApplicationDowntimeScheduleByApplicationName(string applicationName) {
            return base.Channel.GetApplicationDowntimeScheduleByApplicationName(applicationName);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.DTS.Schedule> GetApplicationDowntimeScheduleByApplicationNameAsync(string applicationName) {
            return base.Channel.GetApplicationDowntimeScheduleByApplicationNameAsync(applicationName);
        }
    }
}
