//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeveloperPortal.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeveloperPortal.Domain.Resources.EmailTemplate", typeof(EmailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting Application.
        /// </summary>
        public static string ET_AcceptingApplication {
            get {
                return ResourceManager.GetString("ET_AcceptingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Application Decline.
        /// </summary>
        public static string ET_ApplicationDecline {
            get {
                return ResourceManager.GetString("ET_ApplicationDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Transfer.
        /// </summary>
        public static string ET_ClientTransfer {
            get {
                return ResourceManager.GetString("ET_ClientTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction Notes on Your PMP.
        /// </summary>
        public static string ET_CorrectionNotesOnYourPMP {
            get {
                return ResourceManager.GetString("ET_CorrectionNotesOnYourPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction Notes on Your Property Listing.
        /// </summary>
        public static string ET_CorrectionNotesOnYourPropertyListing {
            get {
                return ResourceManager.GetString("ET_CorrectionNotesOnYourPropertyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Approval on Intranet.
        /// </summary>
        public static string ET_DocumentApprovalonIntranet {
            get {
                return ResourceManager.GetString("ET_DocumentApprovalonIntranet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email to applicant signing up.
        /// </summary>
        public static string ET_EmailToApplicantSigningUp {
            get {
                return ResourceManager.GetString("ET_EmailToApplicantSigningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email to person signing up.
        /// </summary>
        public static string ET_EmailToPersonSigningUp {
            get {
                return ResourceManager.GetString("ET_EmailToPersonSigningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email to person who reset password.
        /// </summary>
        public static string ET_EmailToPersonWhoResetPassword {
            get {
                return ResourceManager.GetString("ET_EmailToPersonWhoResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Listing for Review To Next Reviewer.
        /// </summary>
        public static string ET_ForwardToNextReviewer {
            get {
                return ResourceManager.GetString("ET_ForwardToNextReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMP for Review To Next Reviewer.
        /// </summary>
        public static string ET_ForwardToNextReviewerPMP {
            get {
                return ResourceManager.GetString("ET_ForwardToNextReviewerPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HA Account Approval.
        /// </summary>
        public static string ET_HAAccountApproval {
            get {
                return ResourceManager.GetString("ET_HAAccountApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRM Pre-Application Submission.
        /// </summary>
        public static string ET_HRMApplicationSubmission {
            get {
                return ResourceManager.GetString("ET_HRMApplicationSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAHSA/CES Plan.
        /// </summary>
        public static string ET_LAHSA_CES_Plan {
            get {
                return ResourceManager.GetString("ET_LAHSA_CES_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing - Property Changed to In Development.
        /// </summary>
        public static string ET_Listing_PropertyChangedToInDevelopment {
            get {
                return ResourceManager.GetString("ET_Listing_PropertyChangedToInDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - 2 days Reminder before Property close.
        /// </summary>
        public static string ET_MS_2DaysReminderbeforePropertyClose {
            get {
                return ResourceManager.GetString("ET_MS_2DaysReminderbeforePropertyClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Closed for Application.
        /// </summary>
        public static string ET_MS_AffordablePropertyClosedforApplication {
            get {
                return ResourceManager.GetString("ET_MS_AffordablePropertyClosedforApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property In Development for Affordable.
        /// </summary>
        public static string ET_MS_AffordablePropertyInDevelopment {
            get {
                return ResourceManager.GetString("ET_MS_AffordablePropertyInDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Open for Application.
        /// </summary>
        public static string ET_MS_AffordablePropertyOpenforApplication {
            get {
                return ResourceManager.GetString("ET_MS_AffordablePropertyOpenforApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Closed Automatically on waitlist.
        /// </summary>
        public static string ET_MS_PropertyClosedAutomaticallyonWaitlist {
            get {
                return ResourceManager.GetString("ET_MS_PropertyClosedAutomaticallyonWaitlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Closed Submit for waitlist.
        /// </summary>
        public static string ET_MS_PropertyClosedSubmitforWaitlist {
            get {
                return ResourceManager.GetString("ET_MS_PropertyClosedSubmitforWaitlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Open for Market.
        /// </summary>
        public static string ET_MS_PropertyOpenforMarket {
            get {
                return ResourceManager.GetString("ET_MS_PropertyOpenforMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Open for Pre-application.
        /// </summary>
        public static string ET_MS_PropertyOpenforPreApplication {
            get {
                return ResourceManager.GetString("ET_MS_PropertyOpenforPreApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Accepting Application.
        /// </summary>
        public static string ET_NotAcceptingApplication {
            get {
                return ResourceManager.GetString("ET_NotAcceptingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O/PM Submits QR for the Quarter.
        /// </summary>
        public static string ET_OPMSubmitQRForQuarter {
            get {
                return ResourceManager.GetString("ET_OPMSubmitQRForQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O/PM Submits Revision QR for the Quarter.
        /// </summary>
        public static string ET_OPMSubmitRevisionQRForQuarter {
            get {
                return ResourceManager.GetString("ET_OPMSubmitRevisionQRForQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM or Owner Submits Property Listing.
        /// </summary>
        public static string ET_PMOwnerSubmitsListing {
            get {
                return ResourceManager.GetString("ET_PMOwnerSubmitsListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM or Owner Submits PMP.
        /// </summary>
        public static string ET_PMOwnerSubmitsPMP {
            get {
                return ResourceManager.GetString("ET_PMOwnerSubmitsPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property changed to Waitlist.
        /// </summary>
        public static string ET_PropertyChangedToWaitlist {
            get {
                return ResourceManager.GetString("ET_PropertyChangedToWaitlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly Report Approved.
        /// </summary>
        public static string ET_QRApproved {
            get {
                return ResourceManager.GetString("ET_QRApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRAUVacant.
        /// </summary>
        public static string ET_QRAUVacant {
            get {
                return ResourceManager.GetString("ET_QRAUVacant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly Report Denied.
        /// </summary>
        public static string ET_QRDenied {
            get {
                return ResourceManager.GetString("ET_QRDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRSubmissionPeriodBegin.
        /// </summary>
        public static string ET_QRSubmissionPeriodBeginMail {
            get {
                return ResourceManager.GetString("ET_QRSubmissionPeriodBeginMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRSubmissionPeriodEnd.
        /// </summary>
        public static string ET_QRSubmissionPeriodEndMail {
            get {
                return ResourceManager.GetString("ET_QRSubmissionPeriodEndMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRUpcomingUnitVacancy.
        /// </summary>
        public static string ET_QRUpcomingUnitVacancy {
            get {
                return ResourceManager.GetString("ET_QRUpcomingUnitVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Listing Updates.
        /// </summary>
        public static string ET_ReviewListingUpdates {
            get {
                return ResourceManager.GetString("ET_ReviewListingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review PMP Updates.
        /// </summary>
        public static string ET_ReviewPMPUpdates {
            get {
                return ResourceManager.GetString("ET_ReviewPMPUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Correction Requested for Quarterly Reports.
        /// </summary>
        public static string ET_StaffCorrectionRequestedForQuarter {
            get {
                return ResourceManager.GetString("ET_StaffCorrectionRequestedForQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Wait List Application.
        /// </summary>
        public static string ET_SubmitWaitListApplication {
            get {
                return ResourceManager.GetString("ET_SubmitWaitListApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Cert Exp 30 Days.
        /// </summary>
        public static string ET_TrainingCertExp30Days {
            get {
                return ResourceManager.GetString("ET_TrainingCertExp30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Cert Exp 60 Days.
        /// </summary>
        public static string ET_TrainingCertExp60Days {
            get {
                return ResourceManager.GetString("ET_TrainingCertExp60Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Cert Expired.
        /// </summary>
        public static string ET_TrainingCertExpired {
            get {
                return ResourceManager.GetString("ET_TrainingCertExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Reg 3 Days Reminder.
        /// </summary>
        public static string ET_TrainingReg3DaysReminder {
            get {
                return ResourceManager.GetString("ET_TrainingReg3DaysReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Registration Cancel.
        /// </summary>
        public static string ET_TrainingRegistrationCancel {
            get {
                return ResourceManager.GetString("ET_TrainingRegistrationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Registration for Employee.
        /// </summary>
        public static string ET_TrainingRegistrationforEmployee {
            get {
                return ResourceManager.GetString("ET_TrainingRegistrationforEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Registration for PM.
        /// </summary>
        public static string ET_TrainingRegistrationforPM {
            get {
                return ResourceManager.GetString("ET_TrainingRegistrationforPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Session Cancel.
        /// </summary>
        public static string ET_TrainingSessionCancel {
            get {
                return ResourceManager.GetString("ET_TrainingSessionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CWL Close Date.
        /// </summary>
        public static string ET_UpdateCWLCloseDate {
            get {
                return ResourceManager.GetString("ET_UpdateCWLCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update HRM Pre-Application.
        /// </summary>
        public static string ET_UpdateHRMApplication {
            get {
                return ResourceManager.GetString("ET_UpdateHRMApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile Applicant.
        /// </summary>
        public static string ET_UpdateProfileApplicant {
            get {
                return ResourceManager.GetString("ET_UpdateProfileApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile Owner.
        /// </summary>
        public static string ET_UpdateProfileOwner {
            get {
                return ResourceManager.GetString("ET_UpdateProfileOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates on Property in Your Profile.
        /// </summary>
        public static string ET_UpdatesOnPropertyInYourProfile {
            get {
                return ResourceManager.GetString("ET_UpdatesOnPropertyInYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates on Your Property Listing.
        /// </summary>
        public static string ET_UpdatesOnYourPropertyListing {
            get {
                return ResourceManager.GetString("ET_UpdatesOnYourPropertyListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PMP is approved.
        /// </summary>
        public static string ET_UpdatesOnYourPropertyPMP {
            get {
                return ResourceManager.GetString("ET_UpdatesOnYourPropertyPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Certificate is uploaded on your PMP.
        /// </summary>
        public static string ET_UploadFinalCertificate {
            get {
                return ResourceManager.GetString("ET_UploadFinalCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary Certificate is uploaded on your PMP.
        /// </summary>
        public static string ET_UploadPreliminaryCertificate {
            get {
                return ResourceManager.GetString("ET_UploadPreliminaryCertificate", resourceCulture);
            }
        }
    }
}
