//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCIDLA.ServiceClient.VScan {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VscanResult", Namespace="http://schemas.datacontract.org/2004/07/VscanWcf")]
    [System.SerializableAttribute()]
    public partial class VscanResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DefinitionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefinitionRevisionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InfectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ScanDurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DefinitionDate {
            get {
                return this.DefinitionDateField;
            }
            set {
                if ((this.DefinitionDateField.Equals(value) != true)) {
                    this.DefinitionDateField = value;
                    this.RaisePropertyChanged("DefinitionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefinitionRevisionNumber {
            get {
                return this.DefinitionRevisionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DefinitionRevisionNumberField, value) != true)) {
                    this.DefinitionRevisionNumberField = value;
                    this.RaisePropertyChanged("DefinitionRevisionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Infected {
            get {
                return this.InfectedField;
            }
            set {
                if ((this.InfectedField.Equals(value) != true)) {
                    this.InfectedField = value;
                    this.RaisePropertyChanged("Infected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ScanDuration {
            get {
                return this.ScanDurationField;
            }
            set {
                if ((this.ScanDurationField.Equals(value) != true)) {
                    this.ScanDurationField = value;
                    this.RaisePropertyChanged("ScanDuration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VScan.Ivscan")]
    public interface Ivscan {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ivscan/scan", ReplyAction="http://tempuri.org/Ivscan/scanResponse")]
        HCIDLA.ServiceClient.VScan.VscanResult scan(byte[] bytesToScan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ivscan/scan", ReplyAction="http://tempuri.org/Ivscan/scanResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.VScan.VscanResult> scanAsync(byte[] bytesToScan);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IvscanChannel : HCIDLA.ServiceClient.VScan.Ivscan, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IvscanClient : System.ServiceModel.ClientBase<HCIDLA.ServiceClient.VScan.Ivscan>, HCIDLA.ServiceClient.VScan.Ivscan {
        
        public IvscanClient() {
        }
        
        public IvscanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IvscanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IvscanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IvscanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HCIDLA.ServiceClient.VScan.VscanResult scan(byte[] bytesToScan) {
            return base.Channel.scan(bytesToScan);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.VScan.VscanResult> scanAsync(byte[] bytesToScan) {
            return base.Channel.scanAsync(bytesToScan);
        }
    }
}
