//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCIDLA.ServiceClient.DMS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HCIDLA.ServiceClient.DMS.SearchResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HCIDLA.ServiceClient.DMS.ContentRetrievalResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HCIDLA.ServiceClient.DMS.DeleteResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HCIDLA.ServiceClient.DMS.DeleteItemResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HCIDLA.ServiceClient.DMS.UploadResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HCIDLA.ServiceClient.DMS.GetVersionResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCIDLA.ServiceClient.DMS.Status ReturnStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCIDLA.ServiceClient.DMS.Status ReturnStatus {
            get {
                return this.ReturnStatusField;
            }
            set {
                if ((this.ReturnStatusField.Equals(value) != true)) {
                    this.ReturnStatusField = value;
                    this.RaisePropertyChanged("ReturnStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResponse", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
    [System.SerializableAttribute()]
    public partial class SearchResponse : HCIDLA.ServiceClient.DMS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentRetrievalResponse", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
    [System.SerializableAttribute()]
    public partial class ContentRetrievalResponse : HCIDLA.ServiceClient.DMS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileStreamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileExtension {
            get {
                return this.FileExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.FileExtensionField, value) != true)) {
                    this.FileExtensionField = value;
                    this.RaisePropertyChanged("FileExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileStream {
            get {
                return this.FileStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.FileStreamField, value) != true)) {
                    this.FileStreamField = value;
                    this.RaisePropertyChanged("FileStream");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteResponse", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
    [System.SerializableAttribute()]
    public partial class DeleteResponse : HCIDLA.ServiceClient.DMS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCIDLA.ServiceClient.DMS.DeleteItemResponse[] ItemStatusListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCIDLA.ServiceClient.DMS.DeleteItemResponse[] ItemStatusList {
            get {
                return this.ItemStatusListField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemStatusListField, value) != true)) {
                    this.ItemStatusListField = value;
                    this.RaisePropertyChanged("ItemStatusList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteItemResponse", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
    [System.SerializableAttribute()]
    public partial class DeleteItemResponse : HCIDLA.ServiceClient.DMS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FailedGuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FailedGuid {
            get {
                return this.FailedGuidField;
            }
            set {
                if ((this.FailedGuidField.Equals(value) != true)) {
                    this.FailedGuidField = value;
                    this.RaisePropertyChanged("FailedGuid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadResponse", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF.DMSSvc")]
    [System.SerializableAttribute()]
    public partial class UploadResponse : HCIDLA.ServiceClient.DMS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UniqueIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UniqueId {
            get {
                return this.UniqueIdField;
            }
            set {
                if ((this.UniqueIdField.Equals(value) != true)) {
                    this.UniqueIdField = value;
                    this.RaisePropertyChanged("UniqueId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVersionResponse", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF.DMSSvc")]
    [System.SerializableAttribute()]
    public partial class GetVersionResponse : HCIDLA.ServiceClient.DMS.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Versions {
            get {
                return this.VersionsField;
            }
            set {
                if ((this.VersionsField.Equals(value) != true)) {
                    this.VersionsField = value;
                    this.RaisePropertyChanged("Versions");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DMSFault", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
    [System.SerializableAttribute()]
    public partial class DMSFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchParametersBase", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF.DMSSvc")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HCIDLA.ServiceClient.DMS.ReportParameters))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HCIDLA.ServiceClient.DMS.SearchParameters))]
    public partial class SearchParametersBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid ApplicationIdField;
        
        private HCIDLA.ServiceClient.DMS.DocType DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HCIDLA.ServiceClient.DMS.SysFieldType[] SystemFieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public HCIDLA.ServiceClient.DMS.DocType DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((this.DocumentTypeField.Equals(value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HCIDLA.ServiceClient.DMS.SysFieldType[] SystemFields {
            get {
                return this.SystemFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemFieldsField, value) != true)) {
                    this.SystemFieldsField = value;
                    this.RaisePropertyChanged("SystemFields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportParameters", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF.DMSSvc")]
    [System.SerializableAttribute()]
    public partial class ReportParameters : HCIDLA.ServiceClient.DMS.SearchParametersBase {
        
        private System.DateTime EndField;
        
        private System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.FieldType, string[]> FieldFiltersField;
        
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.FieldType, string[]> FieldFilters {
            get {
                return this.FieldFiltersField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldFiltersField, value) != true)) {
                    this.FieldFiltersField = value;
                    this.RaisePropertyChanged("FieldFilters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchParameters", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF.DMSSvc")]
    [System.SerializableAttribute()]
    public partial class SearchParameters : HCIDLA.ServiceClient.DMS.SearchParametersBase {
        
        private System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.FieldType, string> MetaDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.FieldType, string> MetaData {
            get {
                return this.MetaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDataField, value) != true)) {
                    this.MetaDataField = value;
                    this.RaisePropertyChanged("MetaData");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocType", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF.DMSSvc")]
    public enum DocType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcHP = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATS_CaseDocuments = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BimsCorrespondence = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BimsEarlyExemption = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CCRIS = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CCRIS_THP = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExemptionClaimForm = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FIMS = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Generic = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIMS = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LandUse = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RSOCertificate = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Payments = 13,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysFieldType", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF.DMSSvc")]
    public enum SysFieldType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileName = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileExtension = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileSize = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MimeType = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalURL = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ModifiedBy = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreatedBy = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastAccessed = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreatedOn = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ModifiedOn = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldType", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF.DMSSvc")]
    public enum FieldType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcHPNumber = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AchpProjectId = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AchpPropertyId = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AmtPd = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        APN = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplicationType = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATSId = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATSDocumentType = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATSFileName = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AttachmentType = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Audience = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Building = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CaseId = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Category = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CkOrCCNum = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultImage = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Description = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileName = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FimsId = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GenericText = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIMSModule = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIMSNumber = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIMSProjUniqueID = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIMSProjectUniqueID = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIMSUploadBy = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIMSUploadDate = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LandUseId = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LevelOrFloor = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrimaryKey = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProcessedDate = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceivedDate = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReferenceNum = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestId = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceYear = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SiteAddress = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StatementNum = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Status = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SubCategory = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemDescription = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Units = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ViewOrder = 40,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileUploadInfo", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF.DMSSvc")]
    [System.SerializableAttribute()]
    public partial class FileUploadInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid ApplicationIdField;
        
        private HCIDLA.ServiceClient.DMS.DocType DocumentTypeField;
        
        private string FileNameField;
        
        private byte[] FileStreamField;
        
        private System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.FieldType, string[]> MetaDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.SysFieldType, string> SysDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public HCIDLA.ServiceClient.DMS.DocType DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((this.DocumentTypeField.Equals(value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] FileStream {
            get {
                return this.FileStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.FileStreamField, value) != true)) {
                    this.FileStreamField = value;
                    this.RaisePropertyChanged("FileStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.FieldType, string[]> MetaData {
            get {
                return this.MetaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDataField, value) != true)) {
                    this.MetaDataField = value;
                    this.RaisePropertyChanged("MetaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.SysFieldType, string> SysData {
            get {
                return this.SysDataField;
            }
            set {
                if ((object.ReferenceEquals(this.SysDataField, value) != true)) {
                    this.SysDataField = value;
                    this.RaisePropertyChanged("SysData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReplaceDataInfo", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF.DMSSvc")]
    [System.SerializableAttribute()]
    public partial class ReplaceDataInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid ApplicationIdField;
        
        private System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.FieldType, string[]> MetaDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.SysFieldType, string> SysDataField;
        
        private System.Guid UniqueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.FieldType, string[]> MetaData {
            get {
                return this.MetaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetaDataField, value) != true)) {
                    this.MetaDataField = value;
                    this.RaisePropertyChanged("MetaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<HCIDLA.ServiceClient.DMS.SysFieldType, string> SysData {
            get {
                return this.SysDataField;
            }
            set {
                if ((object.ReferenceEquals(this.SysDataField, value) != true)) {
                    this.SysDataField = value;
                    this.RaisePropertyChanged("SysData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid UniqueId {
            get {
                return this.UniqueIdField;
            }
            set {
                if ((this.UniqueIdField.Equals(value) != true)) {
                    this.UniqueIdField = value;
                    this.RaisePropertyChanged("UniqueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteFileInfo", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
    [System.SerializableAttribute()]
    public partial class DeleteFileInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] DeleteUniqueIdListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] DeleteUniqueIdList {
            get {
                return this.DeleteUniqueIdListField;
            }
            set {
                if ((object.ReferenceEquals(this.DeleteUniqueIdListField, value) != true)) {
                    this.DeleteUniqueIdListField = value;
                    this.RaisePropertyChanged("DeleteUniqueIdList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DMS.IDMS")]
    public interface IDMS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/GetVersionCount", ReplyAction="http://tempuri.org/IDMS/GetVersionCountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HCIDLA.ServiceClient.DMS.DMSFault), Action="http://tempuri.org/IDMS/GetVersionCountDMSFaultFault", Name="DMSFault", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
        HCIDLA.ServiceClient.DMS.GetVersionResponse GetVersionCount(System.Guid UniqueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/GetVersionCount", ReplyAction="http://tempuri.org/IDMS/GetVersionCountResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.GetVersionResponse> GetVersionCountAsync(System.Guid UniqueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/SearchForm", ReplyAction="http://tempuri.org/IDMS/SearchFormResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HCIDLA.ServiceClient.DMS.DMSFault), Action="http://tempuri.org/IDMS/SearchFormDMSFaultFault", Name="DMSFault", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
        HCIDLA.ServiceClient.DMS.SearchResponse SearchForm(HCIDLA.ServiceClient.DMS.SearchParameters Parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/SearchForm", ReplyAction="http://tempuri.org/IDMS/SearchFormResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.SearchResponse> SearchFormAsync(HCIDLA.ServiceClient.DMS.SearchParameters Parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/UploadFile", ReplyAction="http://tempuri.org/IDMS/UploadFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HCIDLA.ServiceClient.DMS.DMSFault), Action="http://tempuri.org/IDMS/UploadFileDMSFaultFault", Name="DMSFault", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
        HCIDLA.ServiceClient.DMS.UploadResponse UploadFile(HCIDLA.ServiceClient.DMS.FileUploadInfo FInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/UploadFile", ReplyAction="http://tempuri.org/IDMS/UploadFileResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.UploadResponse> UploadFileAsync(HCIDLA.ServiceClient.DMS.FileUploadInfo FInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/GetContentByUnid", ReplyAction="http://tempuri.org/IDMS/GetContentByUnidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HCIDLA.ServiceClient.DMS.DMSFault), Action="http://tempuri.org/IDMS/GetContentByUnidDMSFaultFault", Name="DMSFault", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
        HCIDLA.ServiceClient.DMS.ContentRetrievalResponse GetContentByUnid(System.Guid UniqueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/GetContentByUnid", ReplyAction="http://tempuri.org/IDMS/GetContentByUnidResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.ContentRetrievalResponse> GetContentByUnidAsync(System.Guid UniqueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/ReplaceData", ReplyAction="http://tempuri.org/IDMS/ReplaceDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HCIDLA.ServiceClient.DMS.DMSFault), Action="http://tempuri.org/IDMS/ReplaceDataDMSFaultFault", Name="DMSFault", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
        HCIDLA.ServiceClient.DMS.ResponseBase ReplaceData(HCIDLA.ServiceClient.DMS.ReplaceDataInfo RInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/ReplaceData", ReplyAction="http://tempuri.org/IDMS/ReplaceDataResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.ResponseBase> ReplaceDataAsync(HCIDLA.ServiceClient.DMS.ReplaceDataInfo RInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/DeleteFile", ReplyAction="http://tempuri.org/IDMS/DeleteFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HCIDLA.ServiceClient.DMS.DMSFault), Action="http://tempuri.org/IDMS/DeleteFileDMSFaultFault", Name="DMSFault", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
        HCIDLA.ServiceClient.DMS.DeleteResponse DeleteFile(HCIDLA.ServiceClient.DMS.DeleteFileInfo RInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/DeleteFile", ReplyAction="http://tempuri.org/IDMS/DeleteFileResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.DeleteResponse> DeleteFileAsync(HCIDLA.ServiceClient.DMS.DeleteFileInfo RInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/SearchFormReport", ReplyAction="http://tempuri.org/IDMS/SearchFormReportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HCIDLA.ServiceClient.DMS.DMSFault), Action="http://tempuri.org/IDMS/SearchFormReportDMSFaultFault", Name="DMSFault", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
        HCIDLA.ServiceClient.DMS.SearchResponse SearchFormReport(HCIDLA.ServiceClient.DMS.ReportParameters Parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/SearchFormReport", ReplyAction="http://tempuri.org/IDMS/SearchFormReportResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.SearchResponse> SearchFormReportAsync(HCIDLA.ServiceClient.DMS.ReportParameters Parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/GetXMLForLargeFile", ReplyAction="http://tempuri.org/IDMS/GetXMLForLargeFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HCIDLA.ServiceClient.DMS.DMSFault), Action="http://tempuri.org/IDMS/GetXMLForLargeFileDMSFaultFault", Name="DMSFault", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
        string GetXMLForLargeFile(HCIDLA.ServiceClient.DMS.FileUploadInfo fileUploadInfo, int fileSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/GetXMLForLargeFile", ReplyAction="http://tempuri.org/IDMS/GetXMLForLargeFileResponse")]
        System.Threading.Tasks.Task<string> GetXMLForLargeFileAsync(HCIDLA.ServiceClient.DMS.FileUploadInfo fileUploadInfo, int fileSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/SubmitLargeFile", ReplyAction="http://tempuri.org/IDMS/SubmitLargeFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HCIDLA.ServiceClient.DMS.DMSFault), Action="http://tempuri.org/IDMS/SubmitLargeFileDMSFaultFault", Name="DMSFault", Namespace="http://schemas.datacontract.org/2004/07/HCIDLA.DMS.WCF")]
        HCIDLA.ServiceClient.DMS.ResponseBase SubmitLargeFile(byte[] fileStream, string xmlFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDMS/SubmitLargeFile", ReplyAction="http://tempuri.org/IDMS/SubmitLargeFileResponse")]
        System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.ResponseBase> SubmitLargeFileAsync(byte[] fileStream, string xmlFile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDMSChannel : HCIDLA.ServiceClient.DMS.IDMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DMSClient : System.ServiceModel.ClientBase<HCIDLA.ServiceClient.DMS.IDMS>, HCIDLA.ServiceClient.DMS.IDMS {
        
        public DMSClient() {
        }
        
        public DMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HCIDLA.ServiceClient.DMS.GetVersionResponse GetVersionCount(System.Guid UniqueId) {
            return base.Channel.GetVersionCount(UniqueId);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.GetVersionResponse> GetVersionCountAsync(System.Guid UniqueId) {
            return base.Channel.GetVersionCountAsync(UniqueId);
        }
        
        public HCIDLA.ServiceClient.DMS.SearchResponse SearchForm(HCIDLA.ServiceClient.DMS.SearchParameters Parameters) {
            return base.Channel.SearchForm(Parameters);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.SearchResponse> SearchFormAsync(HCIDLA.ServiceClient.DMS.SearchParameters Parameters) {
            return base.Channel.SearchFormAsync(Parameters);
        }
        
        public HCIDLA.ServiceClient.DMS.UploadResponse UploadFile(HCIDLA.ServiceClient.DMS.FileUploadInfo FInfo) {
            return base.Channel.UploadFile(FInfo);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.UploadResponse> UploadFileAsync(HCIDLA.ServiceClient.DMS.FileUploadInfo FInfo) {
            return base.Channel.UploadFileAsync(FInfo);
        }
        
        public HCIDLA.ServiceClient.DMS.ContentRetrievalResponse GetContentByUnid(System.Guid UniqueId) {
            return base.Channel.GetContentByUnid(UniqueId);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.ContentRetrievalResponse> GetContentByUnidAsync(System.Guid UniqueId) {
            return base.Channel.GetContentByUnidAsync(UniqueId);
        }
        
        public HCIDLA.ServiceClient.DMS.ResponseBase ReplaceData(HCIDLA.ServiceClient.DMS.ReplaceDataInfo RInfo) {
            return base.Channel.ReplaceData(RInfo);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.ResponseBase> ReplaceDataAsync(HCIDLA.ServiceClient.DMS.ReplaceDataInfo RInfo) {
            return base.Channel.ReplaceDataAsync(RInfo);
        }
        
        public HCIDLA.ServiceClient.DMS.DeleteResponse DeleteFile(HCIDLA.ServiceClient.DMS.DeleteFileInfo RInfo) {
            return base.Channel.DeleteFile(RInfo);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.DeleteResponse> DeleteFileAsync(HCIDLA.ServiceClient.DMS.DeleteFileInfo RInfo) {
            return base.Channel.DeleteFileAsync(RInfo);
        }
        
        public HCIDLA.ServiceClient.DMS.SearchResponse SearchFormReport(HCIDLA.ServiceClient.DMS.ReportParameters Parameters) {
            return base.Channel.SearchFormReport(Parameters);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.SearchResponse> SearchFormReportAsync(HCIDLA.ServiceClient.DMS.ReportParameters Parameters) {
            return base.Channel.SearchFormReportAsync(Parameters);
        }
        
        public string GetXMLForLargeFile(HCIDLA.ServiceClient.DMS.FileUploadInfo fileUploadInfo, int fileSize) {
            return base.Channel.GetXMLForLargeFile(fileUploadInfo, fileSize);
        }
        
        public System.Threading.Tasks.Task<string> GetXMLForLargeFileAsync(HCIDLA.ServiceClient.DMS.FileUploadInfo fileUploadInfo, int fileSize) {
            return base.Channel.GetXMLForLargeFileAsync(fileUploadInfo, fileSize);
        }
        
        public HCIDLA.ServiceClient.DMS.ResponseBase SubmitLargeFile(byte[] fileStream, string xmlFile) {
            return base.Channel.SubmitLargeFile(fileStream, xmlFile);
        }
        
        public System.Threading.Tasks.Task<HCIDLA.ServiceClient.DMS.ResponseBase> SubmitLargeFileAsync(byte[] fileStream, string xmlFile) {
            return base.Channel.SubmitLargeFileAsync(fileStream, xmlFile);
        }
    }
}
