//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeveloperPortal.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailAction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailAction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeveloperPortal.Models.Resources.EmailAction", typeof(EmailAction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting Application.
        /// </summary>
        public static string EA_AcceptingApplication {
            get {
                return ResourceManager.GetString("EA_AcceptingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Application Submission.
        /// </summary>
        public static string EA_ApplicationSubmission {
            get {
                return ResourceManager.GetString("EA_ApplicationSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval/Rejection Notification.
        /// </summary>
        public static string EA_ApprovalRejectionNotification {
            get {
                return ResourceManager.GetString("EA_ApprovalRejectionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string EA_ChangePassword {
            get {
                return ResourceManager.GetString("EA_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Transfer.
        /// </summary>
        public static string EA_ClientTransfer {
            get {
                return ResourceManager.GetString("EA_ClientTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline Pre-Application.
        /// </summary>
        public static string EA_DeclineApplication {
            get {
                return ResourceManager.GetString("EA_DeclineApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Certificate is uploaded.
        /// </summary>
        public static string EA_FinalCertificateUploaded {
            get {
                return ResourceManager.GetString("EA_FinalCertificateUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HA Account Approval.
        /// </summary>
        public static string EA_HAAccountApproval {
            get {
                return ResourceManager.GetString("EA_HAAccountApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Pre-application for LAHSA/CES Plan.
        /// </summary>
        public static string EA_LAHSA_CES_Plan {
            get {
                return ResourceManager.GetString("EA_LAHSA_CES_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Property.
        /// </summary>
        public static string EA_LinkProperty {
            get {
                return ResourceManager.GetString("EA_LinkProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing - Property Changed to In Development.
        /// </summary>
        public static string EA_Listing_PropertyChangedToInDevelopment {
            get {
                return ResourceManager.GetString("EA_Listing_PropertyChangedToInDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Intake Correction Required.
        /// </summary>
        public static string EA_ListingIntakeCorrectionRequired {
            get {
                return ResourceManager.GetString("EA_ListingIntakeCorrectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Intake Publish.
        /// </summary>
        public static string EA_ListingIntakePublish {
            get {
                return ResourceManager.GetString("EA_ListingIntakePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - 2 days Reminder before Property close.
        /// </summary>
        public static string EA_MS_2DaysReminderbeforePropertyClose {
            get {
                return ResourceManager.GetString("EA_MS_2DaysReminderbeforePropertyClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Conventinal Property Closed Submit for waitlist.
        /// </summary>
        public static string EA_MS_ConvPropertyClosedSubmitforWaitlist {
            get {
                return ResourceManager.GetString("EA_MS_ConvPropertyClosedSubmitforWaitlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Conventinal Property Open for Pre-application.
        /// </summary>
        public static string EA_MS_ConvPropertyOpenforPreApplication {
            get {
                return ResourceManager.GetString("EA_MS_ConvPropertyOpenforPreApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property In Development for Affordable.
        /// </summary>
        public static string EA_MS_LandUseProjectUnderConstructionorInDevelopment {
            get {
                return ResourceManager.GetString("EA_MS_LandUseProjectUnderConstructionorInDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Open for Application.
        /// </summary>
        public static string EA_MS_OwnerPropertyManagerAcceptingApplications {
            get {
                return ResourceManager.GetString("EA_MS_OwnerPropertyManagerAcceptingApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Closed for Application.
        /// </summary>
        public static string EA_MS_OwnerPropertyManagerNotAcceptingApplications {
            get {
                return ResourceManager.GetString("EA_MS_OwnerPropertyManagerNotAcceptingApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Closed Automatically on waitlist.
        /// </summary>
        public static string EA_MS_PropertyClosedAutomaticallyonWaitlist {
            get {
                return ResourceManager.GetString("EA_MS_PropertyClosedAutomaticallyonWaitlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Closed Submit for waitlist.
        /// </summary>
        public static string EA_MS_PropertyClosedSubmitforWaitlist {
            get {
                return ResourceManager.GetString("EA_MS_PropertyClosedSubmitforWaitlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Open for Market.
        /// </summary>
        public static string EA_MS_PropertyOpenforMarket {
            get {
                return ResourceManager.GetString("EA_MS_PropertyOpenforMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property Open for Pre-application.
        /// </summary>
        public static string EA_MS_PropertyOpenforPreApplication {
            get {
                return ResourceManager.GetString("EA_MS_PropertyOpenforPreApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Reminder 2 Days Before Close Date.
        /// </summary>
        public static string EA_MS_Reminder2DaysBeforeClose {
            get {
                return ResourceManager.GetString("EA_MS_Reminder2DaysBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string EA_MyAccount {
            get {
                return ResourceManager.GetString("EA_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Accepting Application.
        /// </summary>
        public static string EA_NotAcceptingApplication {
            get {
                return ResourceManager.GetString("EA_NotAcceptingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPM Submit Revision QR.
        /// </summary>
        public static string EA_OPMSubmitRevisionQRForQuarter {
            get {
                return ResourceManager.GetString("EA_OPMSubmitRevisionQRForQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPM Submit QR.
        /// </summary>
        public static string EA_OPMSubmitsQRForQuarter {
            get {
                return ResourceManager.GetString("EA_OPMSubmitsQRForQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Owner Submits Listing.
        /// </summary>
        public static string EA_PMOwnerSubmitsListing {
            get {
                return ResourceManager.GetString("EA_PMOwnerSubmitsListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Owner Submits PMP.
        /// </summary>
        public static string EA_PMOwnerSubmitsPMP {
            get {
                return ResourceManager.GetString("EA_PMOwnerSubmitsPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMP Correction Required.
        /// </summary>
        public static string EA_PMPIntakeCorrectionRequired {
            get {
                return ResourceManager.GetString("EA_PMPIntakeCorrectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMP Publish.
        /// </summary>
        public static string EA_PMPIntakePublish {
            get {
                return ResourceManager.GetString("EA_PMPIntakePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary Certificate is uploaded.
        /// </summary>
        public static string EA_PreliminaryCertificateUploaded {
            get {
                return ResourceManager.GetString("EA_PreliminaryCertificateUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS - Property changed to Waitlist.
        /// </summary>
        public static string EA_PropertyChangedToWaitlist {
            get {
                return ResourceManager.GetString("EA_PropertyChangedToWaitlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Approved.
        /// </summary>
        public static string EA_QRApproved {
            get {
                return ResourceManager.GetString("EA_QRApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AU Vacant.
        /// </summary>
        public static string EA_QRAUVacant {
            get {
                return ResourceManager.GetString("EA_QRAUVacant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Denied.
        /// </summary>
        public static string EA_QRDenied {
            get {
                return ResourceManager.GetString("EA_QRDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Submission Period Begin.
        /// </summary>
        public static string EA_QRSubmissionPeriodBegins {
            get {
                return ResourceManager.GetString("EA_QRSubmissionPeriodBegins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AU Vacant in next 60 days.
        /// </summary>
        public static string EA_QRUpcomingUnitVacancy {
            get {
                return ResourceManager.GetString("EA_QRUpcomingUnitVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing for Review.
        /// </summary>
        public static string EA_ReviewToNextReviewer {
            get {
                return ResourceManager.GetString("EA_ReviewToNextReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMP for Review.
        /// </summary>
        public static string EA_ReviewToNextReviewerPMP {
            get {
                return ResourceManager.GetString("EA_ReviewToNextReviewerPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignUp.
        /// </summary>
        public static string EA_Signup {
            get {
                return ResourceManager.GetString("EA_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Correction Requested.
        /// </summary>
        public static string EA_StaffCorrectionRequestedForQuarter {
            get {
                return ResourceManager.GetString("EA_StaffCorrectionRequestedForQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Wait List Application.
        /// </summary>
        public static string EA_SubmitWaitListApplication {
            get {
                return ResourceManager.GetString("EA_SubmitWaitListApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail scheduler training certificate expiration {0} days reminder.
        /// </summary>
        public static string EA_TrainingCertExpReminder {
            get {
                return ResourceManager.GetString("EA_TrainingCertExpReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Confirmation.
        /// </summary>
        public static string EA_TrainingConfirmation {
            get {
                return ResourceManager.GetString("EA_TrainingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail scheduler training registration info 3 days reminder.
        /// </summary>
        public static string EA_TrainingReg3DaysReminder {
            get {
                return ResourceManager.GetString("EA_TrainingReg3DaysReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Registration Cancel.
        /// </summary>
        public static string EA_TrainingRegistrationCancel {
            get {
                return ResourceManager.GetString("EA_TrainingRegistrationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Session Cancel.
        /// </summary>
        public static string EA_TrainingSessionCancel {
            get {
                return ResourceManager.GetString("EA_TrainingSessionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CWL Close Date by OPM.
        /// </summary>
        public static string EA_UpdateCWLCloseDate {
            get {
                return ResourceManager.GetString("EA_UpdateCWLCloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update HRM Pre-Application.
        /// </summary>
        public static string EA_UpdateHRMApplication {
            get {
                return ResourceManager.GetString("EA_UpdateHRMApplication", resourceCulture);
            }
        }
    }
}
