//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCon.Document.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.AssnDocuments = new HashSet<AssnDocument>();
        }
    
        public int DocumentID { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public string FileSize { get; set; }
        public string OtherDocumentType { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string Comment { get; set; }
        public string Attributes { get; set; }
        public Nullable<int> DocumentTemplateID { get; set; }
        public string DocumentNum { get; set; }
        public string DocumentEntity { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ServiceTrackingID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssnDocument> AssnDocuments { get; set; }
        public virtual DocumentTemplate DocumentTemplate { get; set; }
    }
}
