//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComCon.Document.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LutTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LutTemplate()
        {
            this.DocumentTemplates = new HashSet<DocumentTemplate>();
        }
    
        public int LutTemplateID { get; set; }
        public string DocumentType { get; set; }
        public string TemplateName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsObsolete { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> RowID { get; set; }
        public string SampleData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentTemplate> DocumentTemplates { get; set; }
    }
}
